# Change these first
owner: psychonaut-station # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: BYOND Hub
    url: https://www.byond.com/games/hub/exadv1/spacestation13
  - name: Home Page
    url: https://tr.ss13.org
  - name: Game Server
    url: tr-1.ss13.org
    port: 3131
    check: "tcp-ping"
    maxResponseTime: 300
  - name: API (v2)
    url: https://api.ss13.org/v2/server
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Wiki
    url: https://wiki.ss13.org/Ping
    __dangerous__body_down_if_text_missing: "iamaliveandgood31"

status-website:
  cname: status-tr1.ss13.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Psychonaut Station Status
  theme: night
  introTitle: "Psychonaut Station Server Status"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "25 */4 * * *"
  responseTime: "20 */4 * * *"
  staticSite: "0 1 * * *"
  summary: "30 * * * *"
  updateTemplate: "0 0 1 * *"
  updates: "0 3 31 2 1"
  uptime: "*/5 * * * *"

commitMessages:
  commitAuthorName: "loanselotci"
  commitAuthorEmail: "144540560+loanselotci@users.noreply.github.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
